[workspace]
members = ["pac"]

[package]
name = "k230-bare-metal"
version = "0.1.0"
edition = "2021"

[dependencies]
pac = { path = "./pac" }
riscv = "0.12.1"
uart8250 = { version = "0.6.0", features = ["fmt"] }
