# default target

[build]
target = "riscv64gc-unknown-none-elf"


[target.riscv64gc-unknown-none-elf]
rustflags = [
    #"-C",
    #"target-feature=+zve32x",
    # "-C",
    # "link-arg=-Tlink-cpu1.x",
    #   "-C",
    #   "link-arg=--Bstatic",
    #"-C",
    #"link-arg=--relocatable",
]


[unstable]
build-std = ["core"]

[env]
DEFMT_LOG = "info"
